/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nicolasg-chausseau' at '06/02/18 3:58 PM' with Gradle 3.0
 *
 * @author nicolasg-chausseau, @date 06/02/18 3:58 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
